{
 "title": "digitalocean-builder",
 "description": "Generator template for django-prometheus metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_cluster_datasource", "query": "prometheus" },
   { "name": "app" }
  ]
 },
 "panels": [
  {
   "title": "Request Total by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(django_http_requests_total_by_method{method=\"GET\", app=\"$app\"})",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(django_http_requests_total_by_method{method=\"POST\", app=\"$app\"})",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(django_http_requests_total_by_method{method=\"PUT\", app=\"$app\"})",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "title": "Response Size (5 min avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_responses_body_total_bytes_sum{app=\"$app\"}[5m])/rate(django_http_responses_body_total_bytes_count{app=\"$app\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency Quantiles (5 min window)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{app=\"$app\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{app=\"$app\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{app=\"$app\"}[5m])) by (le))",
     "legendFormat": "P75"
    }
   ]
  },
  {
   "title": "CPU Seconds per min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"$app\"}[5m])*5",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database Statements Executed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_db_execute_total{app=\"$app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_db_errors_total{app=\"$app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}