version: '2.1'

services:
  app:
    image: digitalocean-builder${IMAGE_TAG:-:latest}
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - GIT_COMMIT
        - BUILD_NUMBER
    volumes:
      - ./digitalocean-builder:/digitalocean-builder/
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ""
      DATABASE_URL: postgres://postgres:my-secret-pw@db:5432/digitalocean-builder
      DJANGO_SETTINGS_MODULE: 'config.settings.dev'
      DEV: 'True'
    env_file: local.env
    depends_on:
      - db
      - redis

  scheduler:
    image: digitalocean-builder${IMAGE_TAG:-:latest}
    command: bin/scheduler.sh
    volumes:
      - ./digitalocean-builder:/digitalocean-builder/
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ""
      DATABASE_URL: postgres://postgres:my-secret-pw@db:5432/digitalocean-builder
      DJANGO_SETTINGS_MODULE: 'config.settings.dev'
    env_file: local.env
    depends_on:
      - db
      - redis

  # A service that runs a Celery task worker:
  worker:
    image: digitalocean-builder${IMAGE_TAG:-:latest}
    command: bin/worker.sh
    volumes:
      - ./digitalocean-builder:/digitalocean-builder/
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ""
      DATABASE_URL: postgres://postgres:my-secret-pw@db:5432/digitalocean-builder
      DJANGO_SETTINGS_MODULE: 'config.settings.dev'
    env_file: local.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: digitalocean-builder
      POSTGRES_PASSWORD: my-secret-pw
      PGPASSWORD: my-secret-pw
    volumes:
      - .compose-data/postgres-data/:/var/lib/postgresql/data

  redis:
    image: redis

  # This is a development-only sidecar for running tests, etc.
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      args:
        - GIT_COMMIT
        - BUILD_NUMBER
    ports:
      - 127.0.0.1:9922:22
    volumes:
      - .:/digitalocean-builder/
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ""
      DATABASE_URL: postgres://postgres:my-secret-pw@db:5432/digitalocean-builder
      DJANGO_SETTINGS_MODULE: 'config.settings.test'
      DEV: 'True'
    depends_on:
      - db
    env_file: local.env
