FROM python:3.7
ENV PYTHONUNBUFFERED 1

WORKDIR /digitalocean-builder

# Install required python packages
COPY digitalocean-builder/requirements.indexes /digitalocean-builder/
COPY digitalocean-builder/requirements.txt /digitalocean-builder/
RUN pip install -r requirements.txt

# And the dev dependencies
COPY digitalocean-builder/requirements.dev /digitalocean-builder/
RUN pip install -r requirements.dev

# These are defined in Jenkins ENV variables and passed in through docker-compose
ARG GIT_COMMIT=unknown
ARG BUILD_NUMBER=unknown

ENV VERSION="0.1.${BUILD_NUMBER}"
ENV GIT_COMMIT=$GIT_COMMIT

# Setup SSH with the incredibly secure root login
RUN apt-get update \
 && apt-get install -y openssh-server netcat \
 && mkdir /var/run/sshd \
 && echo 'root:password' | chpasswd \
 && sed -i 's/\#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

COPY docker/bashrc.dev /root/.bashrc

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
