appName: "digitalocean-builder"
environment: "staging"
dnsName: "digitalocean-builder-staging.wpesvc.net"
envVars:
  ENVIRONMENT: "staging"

prometheus:
  urlExporter:
    enabled: true
    port: 3000
    path: /metrics
  threadExporter:
    enabled: true
    numThreads: 4  # numThreads equals number of processes in wsgi config

celeryScheduler:
  enabled: true
celeryWorker:
  enabled: true

gcp_endpoints:
  enabled: false
  service: digitalocean-builder-staging.endpoints.wp-engine-corporate.cloud.goog